version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
      - 8081:81
    links:
      - php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./docker/nginx/sites-enabled/node.conf:/etc/nginx/conf.d/sites-enabled/node.conf

  php:
    build: ./docker/php
    expose:
      - 9000
    links:
      - mysql
      - redis
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:3.2.4
    ports:
      - 6379:6379

volumes:
  db-data:
    driver: local