version: "2"

services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
      - 8081:81
    links:
      - php
      - node
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./docker/nginx/sites-enabled/node.conf:/etc/nginx/conf.d/sites-enabled/node.conf

  php:
    build: ./docker/php
    expose:
      - 9000
    links:
      - mysql
      - redis
    volumes:
      - .:/var/www/html

  node:
    image: node:7.4
    volumes:
      - ./node-socket:/var/www/html/node-socket
    ports:
      - 3030:3030
    expose:
      - 3030

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "cluj-startup"
      MYSQL_USER: "homestead"
      MYSQL_PASSWORD: "secret"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:3.2.4
    ports:
      - 6379:6379

volumes:
  db-data:
    driver: local