version: "2"

services:
  nginx:
    # build: ./docker/nginx
    image: nginx:latest
    ports:
      - 8000:80
    links:
      - php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./docker/php
    expose:
      - 9000
    links:
      - mysql
      - redis
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "cluj-startup"
      MYSQL_USER: "homestead"
      MYSQL_PASSWORD: "secret"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:3.2.4
    ports:
      - "6379:6379"

volumes:
  db-data:
    driver: local