name: Deploy the application to Google Cloud Run
on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1

      - name: Login to GitHub Package Registry
        run: docker login docker.pkg.github.com -u utwo -p ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build -t after5app:latest .
      - name: Tag the Docker image
        run: docker tag after5app:latest docker.pkg.github.com/utwo/after5app-backend/after5app
      - name: Push the Docker image to the registry
        run: docker push docker.pkg.github.com/utwo/after5app-backend/after5app
