name: Deploy the application to Google Cloud Run
on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1

      - name: Login to GitHub Package Registry
        run: docker login docker.pkg.github.com -u utwo -p ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build -t after5app:latest .
      - name: Tag the Docker image
        run: docker tag after5app:latest docker.pkg.github.com/utwo/after5app-backend/after5app
      - name: Push the Docker image to the registry
        run: docker push docker.pkg.github.com/utwo/after5app-backend/after5app

      - name: Authenticate into Google Cloud Platform
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

      - name: Install beta commands and deploy on cloud run
        uses: actions/gcloud/cli@master
        with:
          args: "components install beta --quiet && gcloud beta run deploy ${{ secrets.GCLOUD_PROJECT }} --quiet --image docker.pkg.github.com/Utwo/after5app-backend/after5app --project ${{ secrets.GCLOUD_PROJECT }} --region europe-west1 --platform managed"
